package com.fcfc.app

import com.fcfc.app.core.Codec
import com.fcfc.app.crypto.CryptoGroup
import com.fcfc.app.crypto.Primitives
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Byte-for-byte auth contract test — Android client hash vs the REAL web client hash.
 *
 * Expected values were generated by executing the actual web implementation
 * (frontend/src/stores/auth.ts clientPassHash + frontend/src/lib/utils.ts b64u —
 * byte-identical to the deployed bundle's fn Ht) over these SYNTHETIC vectors:
 *   PBKDF2-HMAC-SHA256, iterations=600000, salt=UTF8("fcfc-v1:"+username.toLowerCase()),
 *   password=UTF8(password) untrimmed, dkLen=32 bytes, base64url without padding.
 *
 * These are deterministic test vectors — no real user credentials involved.
 */
class AuthContractTest {

    private data class Vec(val id: String, val u: String, val p: String, val webHash: String)

    private val vectors = listOf(
        Vec("v1", "hashvector_a1", "TestVector-Pass-9001!", "vW5wf4isNne5-yEoM2MTgrZ4mt3wBI2u2tz0YVuJ6Fw"),
        Vec("v2", "HashVector_A1", "TestVector-Pass-9001!", "vW5wf4isNne5-yEoM2MTgrZ4mt3wBI2u2tz0YVuJ6Fw"), // salt lowercases
        Vec("v3", "hashvector_a2", "  padded pass  ", "W7euWRhVh2vplWrngYaPc7snn2_9wv2B5KLFhC18Lec"),     // no trim
        Vec("v4", "hashvector_a3", "পাসওয়ার্ড-১২৩ ✅", "5yElltkIyTl0om9U-qmhlKKe9LzgtGYDbLNx7NEfT3A"),        // UTF-8 multibyte
        Vec("v5", "hashvector_a4", "p@\$\$w0rd_#[big]-42%", "rRxfj-4d71kYQxJbXT4a8C6jOoRJ-bfUnemvmOoqo5g"), // symbols
    )

    /** The exact function the Android login screen calls — must match the web byte-for-byte. */
    @Test
    fun androidClientPassHashMatchesWebByteForByte() = runBlocking {
        for (v in vectors) {
            val android = CryptoGroup.clientPassHash(v.u, v.p)
            assertEquals("web-vs-android hash mismatch [${v.id} user=${v.u}]", v.webHash, android)
        }
    }

    /** Passcode (user-ID + pin) domain — must match web clientPasscodeHash. */
    @Test
    fun androidClientPasscodeHashMatchesWeb() = runBlocking {
        val android = CryptoGroup.clientPasscodeHash("1234567", "654321")
        assertEquals("web-vs-android passcode-hash mismatch", "zEe9sNvj7NUjrj1KMTlsGPKzAyNrB-wCVXVSQbWtn7k", android)
    }

    /** Contract shape: PBKDF2 params + b64u encoding properties. */
    @Test
    fun pbkdf2ContractShape() {
        val salt = Codec.utf8("fcfc-v1:hashvector_a1")
        assertEquals(21, salt.size) // "fcfc-v1:" (8) + "hashvector_a1" (13)
        val dk = Primitives.pbkdf2("TestVector-Pass-9001!", salt, 600_000, 256)
        assertEquals(32, dk.size) // 256 bits
        val enc = Codec.b64u(dk)
        assertEquals(43, enc.length) // 32 bytes -> 43 b64u chars
        assertEquals("vW5wf4isNne5-yEoM2MTgrZ4mt3wBI2u2tz0YVuJ6Fw", enc)
        assertTrue("no padding char", '=' !in enc)
        assertTrue("url-safe alphabet", enc.all { it in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_" })
        // deterministic
        val dk2 = Primitives.pbkdf2("TestVector-Pass-9001!", salt, 600_000, 256)
        assertTrue(dk.contentEquals(dk2))
    }

    /** Known-answer self-test used at login time must pass on this platform. */
    @Test
    fun cryptoSelfTestPasses() {
        Primitives.cryptoSelfTest() // must not throw
    }

    /** Single-iteration reference vectors (computed with the web's WebCrypto PBKDF2). */
    @Test
    fun pbkdf2SingleIterationKat() {
        val salt = Codec.utf8("fcfc-kat")
        assertEquals("MGS2jLNR-od1rCODhAtOsOS4-JLM00EfYuXg_FiwiVs", Codec.b64u(Primitives.pbkdf2("kat", salt, 1, 256)))
        // non-ASCII secret — catches 8-bit-truncating encoders
        assertEquals("kgq9zND1rJ7fcwhZ94QQqsy9YN10wuuLcLKZ-_5G3-Q", Codec.b64u(Primitives.pbkdf2("মাল", salt, 1, 256)))
    }
}
